update the fie gtithup action

diff --git a/.github/workflows/main-2.yml b/.github/workflows/main-2.yml
--- a/.github/workflows/main-2.yml
+++ b/.github/workflows/main-2.yml
@@ -85,9 +85,11 @@ jobs:
           password: ${{ secrets.SSH_PASSWORD }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-            set -e
-
-            cd ${{ secrets.APP_PATH }} || { echo "Path not found: ${{ secrets.APP_PATH }}"; exit 1; }
-            ls -la
-            bash ./deploy.sh
-            echo "Deployed successfully"
+              set -e
+              echo "Current directory: $(pwd)"
+              echo "Listing files:"
+              ls -la
+              cd ${{ secrets.APP_PATH }} || { echo "Path not found: ${{ secrets.APP_PATH }}"; exit 1; }
+              echo "Changed to directory: $(pwd)"
+              bash ./deploy.sh
+              echo "Deployed successfully"
